# Background and foreground colors
background = #391d69
foreground = #ffffff

# Standard colors
palette = 0=#391d69
palette = 1=#dfb8b1
palette = 2=#fbda6e
palette = 3=#ee94b6
palette = 4=#484bac
palette = 5=#cd91cf
palette = 6=#7181cf
palette = 7=#f0cce4

# Bright colors
palette = 8=#b0a1cb
palette = 9=#faf3f2
palette = 10=#fff2c6
palette = 11=#fce2ec
palette = 12=#8183cf
palette = 13=#ebd0ec
palette = 14=#b3bce9
palette = 15=#ffffff
