background            #391d69
foreground            #ffffff

# black
color0  #391d69
color8  #b0a1cb

# red
color1  #dfb8b1
color9  #faf3f2

# green
color2  #fbda6e
color10 #fff2c6

# yellow
color3  #ee94b6
color11 #fce2ec

# blue
color4  #484bac
color12 #8183cf

# magenta
color5  #cd91cf
color13 #ebd0ec

#cyan
color6  #7181cf
color14 #b3bce9

#white
color7  #f0cce4
color15 #ffffff


